name: Git LFS on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Pull LFS files
        run: |
          git lfs pull

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./ 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true
